### ISSUE TITLE
How to create an Admin Acccount?

### ISSUE THREAD

**Issue by MaramHarsha** [6o6o/sci-journal-mgr#5]
I am trying to add new article but i am getting error that i have no privilege permissions. Can you help me out?

**Comment by 6o6o** [comment]
You need to set the necessary permissions for the existing user. In the database open `j_users` table, locate the target user and modify the value in the `priv` column to one of the below. The first admin has to do it manually because the system initially doesn't know who to trust. Then you'll be able to do it on the admin account page of the website.
```
0 - unconfirmed account
1 - guest user, read-only access
2 - editor, can create and modify articles
4 - admin, can assign permissions to users
```

**Comment by MaramHarsha** [comment]
Thank You
